//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package jaxb;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the classes package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _SVariable_QNAME = new QName("", "S-Variable");
    private static final QName _SLabel_QNAME = new QName("", "S-Label");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: classes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SProgram }
     * 
     * @return
     *     the new instance of {@link SProgram }
     */
    public SProgram createSProgram() {
        return new SProgram();
    }

    /**
     * Create an instance of {@link SInstructions }
     * 
     * @return
     *     the new instance of {@link SInstructions }
     */
    public SInstructions createSInstructions() {
        return new SInstructions();
    }

    /**
     * Create an instance of {@link SInstruction }
     * 
     * @return
     *     the new instance of {@link SInstruction }
     */
    public SInstruction createSInstruction() {
        return new SInstruction();
    }

    /**
     * Create an instance of {@link SInstructionArguments }
     * 
     * @return
     *     the new instance of {@link SInstructionArguments }
     */
    public SInstructionArguments createSInstructionArguments() {
        return new SInstructionArguments();
    }

    /**
     * Create an instance of {@link SInstructionArgument }
     * 
     * @return
     *     the new instance of {@link SInstructionArgument }
     */
    public SInstructionArgument createSInstructionArgument() {
        return new SInstructionArgument();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "S-Variable")
    public JAXBElement<String> createSVariable(String value) {
        return new JAXBElement<>(_SVariable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "S-Label")
    public JAXBElement<String> createSLabel(String value) {
        return new JAXBElement<>(_SLabel_QNAME, String.class, null, value);
    }

}
